"""fileds

Revision ID: 3bdaa44ef51c
Revises: fc5526002995
Create Date: 2024-08-02 11:28:39.319571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bdaa44ef51c'
down_revision = 'fc5526002995'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('soft_delete')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.drop_column('soft_delete')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.drop_column('soft_delete')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('soft_delete', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('soft_delete', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('soft_delete', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
