"""changing user

Revision ID: 6753e57f4d04
Revises: 5da2161ed050
Create Date: 2024-07-26 15:26:26.232388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6753e57f4d04'
down_revision = '5da2161ed050'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('contact_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_status', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
