"""changing user

Revision ID: 72cc25a69552
Revises: 
Create Date: 2024-07-26 14:56:35.299245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72cc25a69552'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('contact_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_status', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
