"""user table

Revision ID: 740776bd2497
Revises: 2e3ad5de5f85
Create Date: 2024-07-29 12:58:20.725384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '740776bd2497'
down_revision = '2e3ad5de5f85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_phone_number_key', type_='unique')
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('user_phone_number_key', ['phone_number'])

    # ### end Alembic commands ###
