"""changing comments

Revision ID: 8561be4ec05d
Revises: d49d27ab995b
Create Date: 2024-08-02 11:54:08.958460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8561be4ec05d'
down_revision = 'd49d27ab995b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint('comment_commented_by_fkey', type_='foreignkey')
        batch_op.drop_column('commented_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commented_by', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('comment_commented_by_fkey', 'user', ['commented_by'], ['username'])

    # ### end Alembic commands ###
