"""changing user

Revision ID: 93487ea1766a
Revises: 05e2a09d1149
Create Date: 2024-07-26 15:24:16.786307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93487ea1766a'
down_revision = '05e2a09d1149'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('contact_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_status', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
