"""user table

Revision ID: 94420172ccf1
Revises: e7e4c566b973
Create Date: 2024-07-29 13:07:12.220728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94420172ccf1'
down_revision = 'e7e4c566b973'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.Text(), nullable=True))
        batch_op.drop_column('last_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###
