"""user table

Revision ID: e7e4c566b973
Revises: 81a476c72471
Create Date: 2024-07-29 13:02:40.596746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7e4c566b973'
down_revision = '81a476c72471'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
