"""fileds

Revision ID: fc5526002995
Revises: 74ddf44092dc
Create Date: 2024-08-02 11:26:07.689456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc5526002995'
down_revision = '74ddf44092dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('soft_delete', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('soft_delete', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('soft_delete', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('soft_delete')
        batch_op.drop_column('is_updated_at')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('soft_delete')
        batch_op.drop_column('is_updated_at')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('is_updated_at')
        batch_op.drop_column('soft_delete')

    # ### end Alembic commands ###
